name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        # No need for fetch-depth: 0 unless you need full git history for the build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: main # Deployment branch
          FOLDER: . # Deploys everything in the root directory
          CLEAN: true # Cleans up removed files

      - name: List files
        run: ls -R
